apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.indicadoresService.nombre }}-config
  labels:
    app.kubernetes.io/name: {{ .Values.indicadoresService.nombre }}
    {{- include "solicitudes-gov.labels" . | nindent 4 }}
data:
  INDICADORES_SERVICE_PORT: {{ .Values.indicadoresService.puerto | quote }}
  SQLSERVER_HOST: {{ .Values.externo.sqlserverHost | quote }}
  SQLSERVER_PORT: {{ .Values.externo.sqlserverPort | quote }}
  SQLSERVER_DB_ANALITICA: {{ .Values.indicadoresService.sqlserverDb | quote }}
  RABBITMQ_HOST: {{ .Values.externo.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.externo.rabbitmqPort | quote }}
  KEYCLOAK_ISSUER_URI: {{ .Values.externo.keycloakIssuerUri | quote }}
  KEYCLOAK_JWKS_URI: {{ .Values.externo.keycloakJwksUri | quote }}
  CORS_ORIGENES_PERMITIDOS: {{ .Values.externo.corsOrigenesPermitidos | quote }}
