apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mfeIndicadores.nombre }}
  labels:
    app.kubernetes.io/name: {{ .Values.mfeIndicadores.nombre }}
    {{- include "solicitudes-gov.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.mfeIndicadores.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.mfeIndicadores.nombre }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.mfeIndicadores.nombre }}
        {{- include "solicitudes-gov.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Values.mfeIndicadores.nombre }}
          image: {{ include "solicitudes-gov.imagen" (dict "Values" .Values "imagen" .Values.mfeIndicadores.imagen) }}
          imagePullPolicy: {{ .Values.imagen.politicaDeDescarga }}
          ports:
            - name: http
              containerPort: {{ .Values.mfeIndicadores.puerto }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            {{- toYaml .Values.mfeIndicadores.recursos | nindent 12 }}
