apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.indicadoresService.nombre }}
  labels:
    app.kubernetes.io/name: {{ .Values.indicadoresService.nombre }}
    {{- include "solicitudes-gov.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.indicadoresService.nombre }}
  ports:
    - name: http
      port: {{ .Values.indicadoresService.puerto }}
      targetPort: http
